version: 2
jobs:
  build:
    docker:
      - image: python:3.5-jessie
    steps:
      - checkout
      - restore_cache:
          key: virtualenv-{{ checksum "setup.py" }}
      - run: python3 -m venv venv
      - run: venv/bin/pip install .
      - run: venv/bin/pip install pytest
      - save_cache:
          key: virtualenv-{{ checksum "setup.py" }}
          paths:
            - venv
      - run: venv/bin/py.test tests

