version: 2
jobs:
  build:
    docker:
      - image: python:3.4-jessie
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install -y libcv-dev libopencv-photo-dev libopencv-contrib-dev
      - restore_cache:
          key: virtualenv-{{ checksum "setup.py" }}
      - run: python3 -m venv venv
      - run: venv/bin/pip install .
      - run: venv/bin/pip install pytest
      - run: venv/bin/pip install -r script/linting/requirements.txt
      - save_cache:
          key: virtualenv-{{ checksum "setup.py" }}
          paths:
            - venv
      - run: venv/bin/py.test tests
      - run: script/linting/lint
